### ISSUE TITLE
Statement Id Missing

### ISSUE THREAD

**Issue by kidcajes** [magefm/cdn#15]
Hi,
I encountered this error when I tried to paste the policy in IAM

"Statement is missing required element - Statement "Stmt1393288415000" is missing "Principal" element"

**Comment by kassner** [comment]
@kidcajes I'm guessing that you aren't using the root account to attach the policy to the user. In such case, please refere to [Specifying a Principal in a Policy](http://docs.aws.amazon.com/AmazonS3/latest/dev/s3-bucket-user-policy-specifying-principal-intro.html)

Also, the policy provided here needs to be attached to the user who will upload the images, I did not tested using bucket policies.
